name: army
description: "A new Flutter project inspired by the Russian Army"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI и дизайн
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  flutter_screenutil: ^5.9.0

  # Чистая архитектура + стейт-менеджмент
  flutter_bloc: ^8.1.3
  provider: ^6.1.2

  # Внедрение зависимостей
  get_it: ^7.6.4
  injectable: ^2.3.2

  # Роутинг
  go_router: ^14.0.0

  # Генерация моделей, sealed-классы и сериализация
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # Хранилище данных
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Функциональный стиль и обработка ошибок
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  freezed: ^2.4.7
  json_serializable: ^6.8.0
  injectable_generator: ^2.4.1
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/army_bg.png
